version: '3.5'
services:
  cmdl-parser-php72:
    container_name: cmdl-parser-php72
    build:
      context: ./build/php
      dockerfile: Dockerfile
    image: cmdl-parser-php72:1.0.0
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ../../:/application:cached
    networks:
      - anycontent
networks:
  anycontent:
    driver: "bridge"
    name: "anycontent"